server:
  port: 9002
spring:
   application:
     name: rabbitmq-consumer
   rabbitmq:
     host: 10.154.0.74
     port: 5672
     username: root
     password: root123
     publisher-confirms: true
     virtual-host: /

#压力测试使用相关配置
#pressure:
#  test:
#    consumer:
#      count: 5
#    queue:
#      count: 0

management:
  endpoint:
      metrics:
        enabled: true
#  security:
#    enabled: false